version: '3.7'
  
networks:
  supersetabp:
    external: true

services:
  redis:
    container_name: redis
    image: redis:7.2.2-alpine
    networks:
      - supersetabp
    ports:
      - "6379:6379"
